name: Test and run Prettier

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: 
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Test and run Prettier
        run: |
          npm ci
          npm run unit-tests

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Test and run Prettier
        run: |
          npm ci
          npm run integration-tests

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Test and run Prettier
        run: |
          npm ci
          npm run prettier

